import { useCallback, useEffect, useMemo, useState } from "react";
import sampleBible from "../data/web-bible-sample.json";

const STORAGE_KEY = "scripture-scroll:v1";

function loadState() {
  try {
    const raw = localStorage.getItem(STORAGE_KEY);
    if (!raw) return defaultState();
    const parsed = JSON.parse(raw);
    return { ...defaultState(), ...parsed };
  } catch {
    return defaultState();
  }
}

function defaultState() {
  return {
    index: 0,
    streak: 0,
    lastReadDate: null,
    versesReadToday: 0,
    bookmarks: []
  };
}

function todayKey() {
  return new Date().toISOString().slice(0, 10);
}

function isYesterday(dateKey) {
  const d = new Date(dateKey);
  const y = new Date();
  y.setDate(y.getDate() - 1);
  return d.toISOString().slice(0, 10) === y.toISOString().slice(0, 10);
}

/**
 * Full Bible data is loaded lazily as a static asset from /data/web-bible.json
 * (generated by `npm run fetch-bible`, already included in this project).
 * Fetching it at runtime — rather than bundling it into the JS — keeps the
 * initial app shell small and lets the browser cache the ~5MB file on its own,
 * separately from app code. Falls back to the small bundled sample if the
 * fetch ever fails (e.g. fully offline on first visit, before the service
 * worker has cached it).
 */
async function loadBibleData() {
  try {
    const res = await fetch("/data/web-bible.json");
    if (!res.ok) throw new Error(`Bible data fetch failed: ${res.status}`);
    const verses = await res.json();
    return Array.isArray(verses) && verses.length > 0 ? verses : sampleBible;
  } catch {
    return sampleBible;
  }
}

export function useVerseFeed() {
  const [bible, setBible] = useState(sampleBible);
  const [state, setState] = useState(loadState);

  useEffect(() => {
    loadBibleData().then(setBible);
  }, []);

  useEffect(() => {
    localStorage.setItem(STORAGE_KEY, JSON.stringify(state));
  }, [state]);

  const currentVerse = bible[state.index % bible.length] ?? bible[0];
  const progressPct = useMemo(() => (state.index / Math.max(bible.length - 1, 1)) * 100, [state.index, bible.length]);

  const advance = useCallback(() => {
    setState((prev) => {
      const today = todayKey();
      let streak = prev.streak;
      let versesReadToday = prev.versesReadToday;

      if (prev.lastReadDate !== today) {
        streak = prev.lastReadDate && isYesterday(prev.lastReadDate) ? prev.streak + 1 : 1;
        versesReadToday = 0;
      }

      return {
        ...prev,
        index: (prev.index + 1) % bible.length,
        streak,
        lastReadDate: today,
        versesReadToday: versesReadToday + 1
      };
    });
  }, [bible.length]);

  const toggleBookmark = useCallback((ref) => {
    setState((prev) => {
      const exists = prev.bookmarks.includes(ref);
      return {
        ...prev,
        bookmarks: exists ? prev.bookmarks.filter((b) => b !== ref) : [...prev.bookmarks, ref]
      };
    });
  }, []);

  const currentRef = `${currentVerse.book} ${currentVerse.chapter}:${currentVerse.verse}`;
  const isBookmarked = state.bookmarks.includes(currentRef);

  return {
    currentVerse,
    currentRef,
    advance,
    progressPct,
    streak: state.streak,
    versesReadToday: state.versesReadToday,
    isBookmarked,
    toggleBookmark,
    bookmarkCount: state.bookmarks.length
  };
}
