import { useCallback, useEffect, useMemo, useState } from "react";
import sampleBible from "../data/web-bible-sample.json";
import storyPath from "../data/story-path.json";

const STORAGE_KEY = "scripture-scroll:v1";

function loadState() {
  try {
    const raw = localStorage.getItem(STORAGE_KEY);
    if (!raw) return defaultState();
    const parsed = JSON.parse(raw);
    return { ...defaultState(), ...parsed };
  } catch {
    return defaultState();
  }
}

function defaultState() {
  return {
    index: 0,
    streak: 0,
    lastReadDate: null,
    versesReadToday: 0,
    bookmarks: []
  };
}

function todayKey() {
  return new Date().toISOString().slice(0, 10);
}

function isYesterday(dateKey) {
  const d = new Date(dateKey);
  const y = new Date();
  y.setDate(y.getDate() - 1);
  return d.toISOString().slice(0, 10) === y.toISOString().slice(0, 10);
}

/**
 * Full Bible data is loaded lazily as a static asset from /data/web-bible.json
 * (generated by `npm run fetch-bible`, already included in this project).
 * Fetching it at runtime — rather than bundling it into the JS — keeps the
 * initial app shell small and lets the browser cache the ~5MB file on its own,
 * separately from app code. Falls back to the small bundled sample if the
 * fetch ever fails (e.g. fully offline on first visit, before the service
 * worker has cached it).
 */
async function loadBibleData() {
  try {
    const res = await fetch("/data/web-bible.json");
    if (!res.ok) throw new Error(`Bible data fetch failed: ${res.status}`);
    const verses = await res.json();
    return Array.isArray(verses) && verses.length > 0 ? verses : sampleBible;
  } catch {
    return sampleBible;
  }
}

/**
 * Builds the reading sequence from the curated story path (src/data/story-path.json)
 * instead of raw canonical Genesis-to-Revelation order. The story path picks out the
 * narrative arc of the Bible — creation, the patriarchs, Exodus, judges and kings,
 * exile, the Gospels, Acts, Revelation's closing vision — and skips the genealogies,
 * legal codes, and census lists that don't read as a story even in order.
 *
 * Falls back to the raw array if the story path can't be resolved against whatever
 * Bible data is loaded (e.g. still on the small bundled sample, which only has a
 * couple of chapters).
 */
function buildStorySequence(bible) {
  const byBookChapter = new Map();
  for (const v of bible) {
    const key = `${v.book}|${v.chapter}`;
    if (!byBookChapter.has(key)) byBookChapter.set(key, []);
    byBookChapter.get(key).push(v);
  }

  const sequence = [];
  for (const entry of storyPath) {
    for (const chapter of entry.chapters) {
      const verses = byBookChapter.get(`${entry.book}|${chapter}`);
      if (!verses) continue; // chapter not present in whatever data is currently loaded
      sequence.push(...[...verses].sort((a, b) => a.verse - b.verse));
    }
  }

  return sequence.length > 0 ? sequence : bible;
}

export function useVerseFeed() {
  const [bible, setBible] = useState(sampleBible);
  const [state, setState] = useState(loadState);

  useEffect(() => {
    loadBibleData().then(setBible);
  }, []);

  useEffect(() => {
    localStorage.setItem(STORAGE_KEY, JSON.stringify(state));
  }, [state]);

  const sequence = useMemo(() => buildStorySequence(bible), [bible]);

  const currentVerse = sequence[state.index % sequence.length] ?? sequence[0];
  const progressPct = useMemo(
    () => (state.index / Math.max(sequence.length - 1, 1)) * 100,
    [state.index, sequence.length]
  );

  const advance = useCallback(() => {
    setState((prev) => {
      const today = todayKey();
      let streak = prev.streak;
      let versesReadToday = prev.versesReadToday;

      if (prev.lastReadDate !== today) {
        streak = prev.lastReadDate && isYesterday(prev.lastReadDate) ? prev.streak + 1 : 1;
        versesReadToday = 0;
      }

      return {
        ...prev,
        index: (prev.index + 1) % sequence.length,
        streak,
        lastReadDate: today,
        versesReadToday: versesReadToday + 1
      };
    });
  }, [sequence.length]);

  const toggleBookmark = useCallback((ref) => {
    setState((prev) => {
      const exists = prev.bookmarks.includes(ref);
      return {
        ...prev,
        bookmarks: exists ? prev.bookmarks.filter((b) => b !== ref) : [...prev.bookmarks, ref]
      };
    });
  }, []);

  const currentRef = `${currentVerse.book} ${currentVerse.chapter}:${currentVerse.verse}`;
  const isBookmarked = state.bookmarks.includes(currentRef);

  return {
    currentVerse,
    currentRef,
    advance,
    progressPct,
    streak: state.streak,
    versesReadToday: state.versesReadToday,
    isBookmarked,
    toggleBookmark,
    bookmarkCount: state.bookmarks.length
  };
}
